apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: frontend-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    # cert-manager.io/cluster-issuer: selfsigned-issuer
spec:
  rules:
    - host: flixtube.life
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend-service
                port:
                  number: 30008
    # - host: developer.flixtube.life  # Add this line to specify the new host
    #   http:
    #     paths:
    #       - path: /
    #         pathType: Prefix
    #         backend:
    #           service:
    #             name: grafana  # Update this service name if needed
    #             port:
    #               number: 80
    #             # namespace: grafana
  # tls:
  #   - hosts:
  #       - flixtube.life
  #     secretName: magda-local-cert-tls
