apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: frontend-ingress
  namespace: grafana
  annotations:
    kubernetes.io/ingress.class: "nginx"
    # cert-manager.io/cluster-issuer: selfsigned-issuer
spec:
  rules:
    - host: developer.flixtube.life  # Add this line to specify the new host
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: grafana  # Update this service name if needed
                port:
                  number: 80